# Generated by Django 4.2.17 on 2024-12-27 03:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0))),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount')),
                ('created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offer', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Special offers',
                'ordering': ('-created',),
            },
        ),
    ]
