# Generated by Django 4.2.17 on 2025-01-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
    ]
