# Generated by Django 4.2.17 on 2025-01-27 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_remove_review_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Percentage')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='products.product', verbose_name='Discounted Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounted_products', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'verbose_name': 'Discount Product',
                'verbose_name_plural': 'Discount Products',
                'ordering': ('-created_at',),
            },
        ),
    ]
