from django.urls import path
from .views import *

urlpatterns = [
    path('categories/', GetCategoryView.as_view(), name='get_categories'),
    path('categories/create/', CreateCategoryView.as_view(), name='create_category'),
    path('categories/update/<int:id>/',
         UpdateCategoryView.as_view(), name='update_category'),
    path('categories/delete/<int:id>/',
         DeleteCategoryView.as_view(), name='delete_category'),

    path('products/', GetProductView.as_view(), name='get_products'),
    path('products/create/', CreateProductView.as_view(), name='create_product'),
    path('products/update/<int:id>/',
         UpdateProductView.as_view(), name='update_product'),
    path('products/delete/<int:id>/',
         DeleteProductView.as_view(), name='delete_product'),

    path('products/<int:product_id>/likes/count/',
         GetProductLikeCountView.as_view(), name='get_product_likes_count'),
    path('products/<int:product_id>/likes/create/',
         CreateProductLikeView.as_view(), name='create_product_like'),
    path('products/<int:product_id>/likes/remove/',
         RemoveProductLikeView.as_view(), name='remove_product_like'),

    path('products/<int:product_id>/reviews/',
         GetProductReviewView.as_view(), name='get_product_reviews'),
    path('products/<int:product_id>/reviews/create/',
         CreateProductReviewView.as_view(), name='create_product_review'),
    path('products/reviews/update/<int:review_product_id>/',
         UpdateProductReviewView.as_view(), name='update_product_review'),
    path('products/reviews/delete/<int:review_product_id>/',
         DeleteProductReviewView.as_view(), name='delete_review'),

    path('products/<int:review_id>/likes_dislikes/create/',
         CreateReviewLikeDislikeView.as_view(), name='create_review_like_dislike'),
    path('products/<int:review_id>/likes_dislikes/remove/',
         RemoveReviewLikeDislikeView.as_view(), name='remove_review_like_dislike'),
    path('products/<int:review_id>/likes_dislikes/count/',
         GetReviewLikeDislikeCountView.as_view(), name='get_review_like_dislike_count'),

    path('toprated/', GetTopratedProdView.as_view(),
         name='get_toprated_products'),
    path('toprated/create/', CreateTopratedProdView.as_view(),
         name='create_toprated_product'),
    path('toprated/update/<int:pk>/', UpdateTopratedProdView.as_view(),
         name='update_toprated_product'),
    path('toprated/delete/<int:pk>/', DeleteTopratedProdView.as_view(),
         name='delete_toprated_product'),

    path('onsale/', GetOnsaleProdView.as_view(), name='get_onsale_products'),
    path('onsale/create/', CreateOnsaleProdView.as_view(),
         name='create_onsale_product'),
    path('onsale/update/<int:pk>/', UpdateOnsaleProdView.as_view(),
         name='update_onsale_product'),
    path('onsale/delete/<int:pk>/', DleteOnsaleProdView.as_view(),
         name='delete_onsale_product'),

    path('bestselling/', GetBestsellingView.as_view(),
         name='get_bestselling_products'),
    path('bestselling/create/', CreateBestsellingView.as_view(),
         name='create_bestselling_product'),
    path('bestselling/update/<int:pk>/', UpdateBestsellingView.as_view(),
         name='update_bestselling_product'),
    path('bestselling/delete/<int:pk>/', DeleteBestsellingView.as_view(),
         name='delete_bestselling_product'),

    path('discount/', GetDiscountProductView.as_view(),
         name='get_discount_products'),
    path('discount/create/', CreateDiscountProductView.as_view(),
         name='create_discount_product'),
    path('discount/update/<int:pk>/', UpdateDiscountProductView.as_view(),
         name='update_discount_product'),
    path('discount/delete/<int:pk>/', DeleteDiscountProductView.as_view(),
         name='delete_discount_product'),
]
