# Generated by Django 4.2.17 on 2024-12-25 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='farmer_photos/', verbose_name='Profile Photo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number')),
                ('farm_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Farm Name')),
                ('farm_location', models.TextField(blank=True, null=True, verbose_name='Farm Location')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('products_offered', models.JSONField(blank=True, null=True, verbose_name='Products Offered (JSON)')),
                ('certifications', models.TextField(blank=True, max_length=500, null=True, verbose_name='Certifications')),
                ('social_media_links', models.JSONField(blank=True, null=True, verbose_name='Social Media Links (JSON)')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='customer_photos/', verbose_name='Profile Photo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP Code')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Short Bio')),
                ('preferred_products', models.JSONField(blank=True, null=True, verbose_name='Preferred Products (JSON)')),
                ('purchase_history', models.JSONField(blank=True, null=True, verbose_name='Purchase History (JSON)')),
                ('social_media_links', models.JSONField(blank=True, null=True, verbose_name='Social Media Links (JSON)')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
