# Generated by Django 4.2.17 on 2025-01-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='articles/categories/icons/'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/categories/images/'),
        ),
    ]
