# Generated by Django 4.2.17 on 2025-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/comments/'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
