# Generated by Django 4.2.17 on 2025-01-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_image_alter_articlecategory_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='link',
        ),
    ]
