# Generated by Django 4.2.7 on 2024-01-30 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Additionalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Additional info',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.PositiveBigIntegerField(verbose_name='Product Price')),
                ('old_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Product Old Price')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('additional_info', models.ManyToManyField(blank=True, to='products.additionalinfo')),
                ('category', models.ManyToManyField(to='products.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Shippingfaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Faq',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TopratedProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Toprated Products',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField()),
                ('rate', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.review', verbose_name='Product Review')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Reviews',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='faq',
            field=models.ManyToManyField(blank=True, to='products.shippingfaq'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='productitem_images', to='products.productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productitem_main_image', to='products.productimage'),
        ),
        migrations.CreateModel(
            name='OnsaleProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Onsale Products',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DiscountProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.PositiveBigIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Discount Product',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BestsellingProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Bestselling Product',
                'ordering': ('-created',),
            },
        ),
    ]
