# Generated by Django 4.2.7 on 2024-03-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlecomment_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='name',
        ),
    ]
