from django.urls import path
from .views import *

urlpatterns = [
    path('product_categories/', GetCategoryView.as_view(), name='get_categories'),
    path('single/category/<int:id>/',
         GetCategoryView.as_view(), name='single_category'),
    path('create/category/', CreateCategoryView.as_view(), name='create_category'),
    path('update/category/<int:id>/',
         UpdateCategoryView.as_view(), name='update_category'),
    path('delete/category/<int:id>/',
         DeleteCategoryView.as_view(), name='delete_category'),

    path('all_products/', GetProductView.as_view(), name='get_products'),
    path('single/product/<int:id>/',
         GetProductView.as_view(), name='single_product'),
    path('create/product/', CreateProductView.as_view(), name='create_product'),
    path('update/product/<int:id>/',
         UpdateProductView.as_view(), name='update_product'),
    path('delete/product/<int:id>/',
         DeleteProductView.as_view(), name='delete_product'),

    path('product/<int:product_id>/likes_count/',
         GetProductLikeCountView.as_view(), name='get_product_likes_count'),
    path('product/<int:product_id>/create/likes/',
         CreateProductLikeView.as_view(), name='create_product_like'),
    path('product/<int:product_id>/remove/likes/',
         RemoveProductLikeView.as_view(), name='remove_product_like'),

    path('product/<int:product_id>/all_reviews/',
         GetProductReviewView.as_view(), name='get_product_reviews'),
    path('product/<int:product_id>/create/review/',
         CreateProductReviewView.as_view(), name='create_product_review'),
    path('product/update/review/<int:review_id>',
         UpdateProductReviewView.as_view(), name='update_product_review'),
    path('product/delete/review/<int:review_id>',
         DeleteProductReviewView.as_view(), name='delete_review'),

    path('product/<int:review_id>/create/likes_dislikes/',
         CreateReviewLikeDislikeView.as_view(), name='create_review_like_dislike'),
    path('product/<int:review_id>/remove/likes_dislikes/',
         RemoveReviewLikeDislikeView.as_view(), name='remove_review_like_dislike'),
    path('product/<int:review_id>/count/likes_dislikes/',
         GetReviewLikeDislikeCountView.as_view(), name='get_review_like_dislike_count'),

    path('toprated_prod/', GetTopratedProdView.as_view(),
         name='get_toprated_products'),
    path('create/toprated_prod/', CreateTopratedProdView.as_view(),
         name='create_toprated_product'),
    path('update/toprated_prod/<int:pk>/', UpdateTopratedProdView.as_view(),
         name='update_toprated_product'),
    path('delete/toprated_prod/<int:pk>/', DeleteTopratedProdView.as_view(),
         name='delete_toprated_product'),

    path('onsale_prod/', GetOnsaleProdView.as_view(), name='get_onsale_products'),
    path('create/onsale_prod/', CreateOnsaleProdView.as_view(),
         name='create_onsale_product'),
    path('update/onsale_prod/<int:pk>/', UpdateOnsaleProdView.as_view(),
         name='update_onsale_product'),
    path('delete/onsale_prod/<int:pk>/', DleteOnsaleProdView.as_view(),
         name='delete_onsale_product'),

    path('bestselling_prod/', GetBestsellingView.as_view(),
         name='get_bestselling_products'),
    path('create/bestselling_prod/', CreateBestsellingView.as_view(),
         name='create_bestselling_product'),
    path('update/bestselling_prod/<int:pk>/', UpdateBestsellingView.as_view(),
         name='update_bestselling_product'),
    path('delete/bestselling_prod/<int:pk>/', DeleteBestsellingView.as_view(),
         name='delete_bestselling_product'),

    path('discount_prod/', GetDiscountProductView.as_view(),
         name='get_discount_products'),
    path('create/discount_prod/', CreateDiscountProductView.as_view(),
         name='create_discount_product'),
    path('update/discount_prod/<int:pk>/', UpdateDiscountProductView.as_view(),
         name='update_discount_product'),
    path('delete/discount_prod/<int:pk>/', DeleteDiscountProductView.as_view(),
         name='delete_discount_product'),
]
