# Generated by Django 4.2.17 on 2025-01-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_address_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal'), ('credit_card', 'Credit Card')], max_length=50),
        ),
    ]
