# Generated by Django 4.2.17 on 2025-01-28 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cartproduct_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_status', models.CharField(choices=[('received', 'Order Received'), ('processing', 'Order Processing'), ('shipped', 'Shipped'), ('completed', 'Order Completed'), ('canceled', 'Order Canceled')], default='received', max_length=50)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders_as_farmer', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='payment.order')),
                ('products', models.ManyToManyField(related_name='sub_orders', to='cart.cartproduct')),
            ],
            options={
                'verbose_name': 'Sub Order',
                'verbose_name_plural': 'Sub Orders',
            },
        ),
    ]
