# Generated by Django 4.2.17 on 2025-02-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
